# Specify the base image

FROM node:16-alpine

#Change working dir

WORKDIR /app

# Download and install some dependencies

COPY package.json .
RUN npm install
RUN mkdir -p node_modules/.cache && chmod -R 777 node_modules/.cache
COPY . .

# Tell the image what to do on start of the container 

CMD ["npm", "run", "start"]
